CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

     username VARCHAR(50) NOT NULL,
     email VARCHAR(150) NOT NULL,
     password_hash VARCHAR(255) NOT NULL,
     full_name VARCHAR(150) NOT NULL,

     role VARCHAR(20) NOT NULL DEFAULT 'USER',
     status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

     CONSTRAINT chk_users_username_not_blank
        CHECK (TRIM(username) <> ''),

     CONSTRAINT chk_users_email_not_blank
        CHECK (TRIM(email) <> ''),

     CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'ADMIN')),

     CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

CREATE UNIQUE INDEX uk_users_username_lower
    ON users (LOWER(username));

CREATE UNIQUE INDEX uk_users_email_lower
    ON users (LOWER(email));

CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    wallet_number VARCHAR(20) NOT NULL,
    owner_user_id BIGINT,
    wallet_type VARCHAR(20) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',

    balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    daily_transfer_limit NUMERIC(19,2) NOT NULL DEFAULT 100000000,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_wallets_owner
        FOREIGN KEY (owner_user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_wallets_wallet_number
    UNIQUE (wallet_number),

    CONSTRAINT chk_wallets_number
    CHECK (wallet_type IN ('USER', 'SYSTEM')),

    CONSTRAINT chk_wallets_status
    CHECK (status IN ('ACTIVE', 'LOCKED', 'CLOSED')),

    CONSTRAINT chk_wallets_balance
    CHECK (balance >= 0),

    CONSTRAINT chk_wallets_daily_limit
    CHECK (daily_transfer_limit >= 0),

    CONSTRAINT chk_wallets_owner
    CHECK (
        (wallet_type = 'USER' AND owner_user_id IS NOT NULL)
        OR
        (wallet_type = 'SYSTEM' AND owner_user_id IS NULL)

    )
);

    CREATE UNIQUE INDEX uk_wallets_owner_currency
    ON wallets (owner_user_id, currency)
    WHERE owner_user_id IS NOT NULL;

    CREATE INDEX idx_wallets_status
    ON wallets (status);
