ALTER TABLE ledger_entries
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Start after existing IDs, including entries previously inserted with explicit IDs.
SELECT setval(
    pg_get_serial_sequence('ledger_entries', 'id'),
    COALESCE((SELECT MAX(id) FROM ledger_entries), 0) + 1,
    false
);
